project:
  type: website
  output-dir: docs

# Meta
description-meta: "Academic website of Danielle Cosme, PhD"
author-meta: "Danielle Cosme, PhD"

website:
  title: "Danielle Cosme"
  # image: "https://quarto.org/quarto.png"
  description: "Academic website of Danielle Cosme, PhD"

  navbar:
    # background: light  # You can change the background color here

    # left:   # You can comment out all navigation items here if you just like to keep the index page only
     # - text: Home
     #   href: index.qmd
      # - text: About
      #   menu:
      #     - text: News
      #       href: posts.qmd#category=news
      #     - text: Events
      #       href: posts.qmd#category=event
      #     - text: Contact
      #       href: contact.qmd
      # - text: Research
      #   menu:
      #     - text: List of Publications
      #       href: publications.qmd
      #     - text: Selected Papers
      #       href: posts.qmd#category=paper
      #     - text: Grants
      #       href: projects.qmd
      # - text: Teaching # Comment the Teaching part out to remove the Teaching page
      #   href: teaching.qmd
      # - text: Outreach
      #   menu:
      #   - text: Presentations
      #     href: posts.qmd#category=presentation
      # - text: Group   # Comment the Group part out to remove the Group page
      #   href: people.qmd

    right:
      - text: Research
        menu:
          - text: Publications
            href: publications.qmd
          # - text: Selected Papers
          #   href: posts.qmd#category=paper
          - text: Grants
            href: grants.qmd
      - text: Teaching # Comment the Teaching part out to remove the Teaching page
        href: teaching.qmd
      # - text: Outreach
      #   menu:
      #   - text: Presentations
      #     href: posts.qmd#category=presentation
      # - text: Group   # Comment the Group part out to remove the Group page
      #   href: people.qmd
      - text: CV
        href: files/cv.pdf
      - icon: github
        href: https://github.com/dcosme
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/dcosme.bsky.social
        target: _blank
      # - icon: rss
      #   href: posts.xml
      #   target: _blank

  page-navigation: true

  page-footer:
    left: "Danielle Cosme &copy; <script>document.write(new Date().getFullYear())</script>"
    center: "Build on [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)"
    right:
      - icon: github
        href: https://github.com/dcosme
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/dcosme.bsky.social
        target: _blank
      # - icon: rss
      #   href: posts.xml
      #   target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true

  draft-mode: unlinked

  repo-url: https://github.com/dcosme/dcosme.github.io
#  repo-actions: [edit, issue, source]

  open-graph: true

  twitter-card: false
#  card-style: summary

  site-url: "https://dcosme.github.io"

  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true

# bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme:
      - united
      - styles.scss
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/dcosme\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

