---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
page-layout: full
execute: 
  echo: false
  message: false
  warning: false
  freeze: true
format: html
toc: true
toc-location: left
---

<!--Include academic icons or buttons-->

{{< include /files/includes/_academic.qmd >}}

<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>


```{r setup}
source("_functions.R")
missing_dois = c("10.31234/osf.io/rfh63_v1", "10.31234/osf.io/k8n7c_v2")
pubs_ignore = "W4255871580|W4251435941|W4212930328|W3161562742|W4280624121|W4235325902|W3166337729|W4398133639|W4402350098|W4200202235|W3158511265|W3124003809|W3037890655|W7111893095|W3203052327|W2776197114|W4415985991"
id = "0000-0001-8956-4053"

non_preprints = data.frame(citation = c("Okker-Edging, K., Porter, B., Liu, A., Noh, D. J., Lydic, K., Muzekari, B., Lewis, T., Torres-Grillo, O., Falk, E. B., Tan, A. S. L., Cosme, D. (Submitted) Youth Participatory Action Communication Research to Address Environmental Health and Climate Change: A Case Study Bridging Graduate and High School Classrooms")) %>%
  mutate(citation = as.list(citation),
         publication_date = c("2025-08-15"),
         doi = NA,
         url = NA,
         pdf_url = NA)

in_press = data.frame(citation = c("Fuchs, M., Boyd, Z. M., Schwarze, A., Cosme, D., Stanoi, O., Kang, Y., Kowatsch, T., von Wangenheim, F., Bassett, D. S., Ochsner, K., Lydon Staley, D. M., Falk, E. B., Mucha, P. J., Jovanova, M. (In Press) Predicting Individual Differences in Digital Alcohol Intervention Effectiveness Through Multimodal Data. npj Digital Medicine.")) %>%
  mutate(citation = as.list(citation),
         publication_date = c("2026-01-08"),
         doi = NA,
         url = NA,
         pdf_url = NA)

#pubs = fetch_pubs(id = id, missing_dois = missing_dois, pubs_ignore = pubs_ignore)
#saveRDS(pubs, "pubs.RDS")
pubs = readRDS("pubs.RDS")
```

## Preprints & submitted 
```{r}
make_pub_list(filter(pubs, type == "preprint" & !doi %in% c("10.31234/osf.io/bj857_v2", "10.31234/osf.io/86n3b", "10.31234/osf.io/kyzh9_v1")) %>% 
                select(citation, publication_date, doi, url, pdf_url) %>%
                bind_rows(non_preprints),
              type = "preprint")
```

## Published journal articles
### 2026 & in press
```{r}
make_pub_list(in_press) #%>% bind_rows(filter(pubs, grepl("^2026", publication_date))))
```

### 2025
```{r}
make_pub_list(filter(pubs, grepl("^2025", publication_date))) 
```

### 2023
```{r}
make_pub_list(filter(pubs, grepl("^2023", publication_date))) 
```

### 2022
```{r}
make_pub_list(filter(pubs, grepl("^2022", publication_date))) 
```

### 2021
```{r}
make_pub_list(filter(pubs, grepl("^2021", publication_date))) 
```

### 2020
```{r}
make_pub_list(filter(pubs, grepl("^2020", publication_date) & !type == "dissertation")) 
```

### 2019
```{r}
make_pub_list(filter(pubs, grepl("^2019", publication_date))) 
```

### 2018
```{r}
make_pub_list(filter(pubs, grepl("^2018", publication_date))) 
```

### 2015
```{r}
make_pub_list(filter(pubs, grepl("^2015", publication_date))) 
```

## Dissertation
```{r}
make_pub_list(filter(pubs, type == "dissertation")) 
```
